S1A:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_hy2B"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
    recalibration: False
S1B:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_hy2B"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
    recalibration: False
RS2:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_hy2B"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: False
    recalibration: False
RCM:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_hy2B"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
    recalibration: False
