S1A:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
S1B:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
RS2:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_rs2_v2"
    apply_flattening: False
RCM:
    GMF_VV_NAME: "cmod5n"
    GMF_VH_NAME: "gmf_rcm_noaa"
    apply_flattening: True
