name: Build and Upload Conda Package

on:
  workflow_run:
    workflows: ["Upload package to PyPI"]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  build-and-upload-conda-package:
    if: true 
    runs-on: ubuntu-latest
    #${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install conda-build
        run: |
          conda config --set always_yes yes
          conda install -y -c conda-forge conda-build

      - name: Ensure Conda is initialized
        shell: bash -l {0}
        run: conda init bash

      - name: Build and Upload Conda package
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          source ~/conda/bin/activate base
          cd recipe
          conda-build . --token $ANACONDA_TOKEN --user tcevaer -c tcevaer -c conda-forge
