name: Upload package to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to PyPI
    container: ghcr.io/osgeo/gdal:alpine-normal-latest
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3

      - name: Update
        run: |
                apt-get update
                apt-get -y install software-properties-common
                add-apt-repository -y ppa:deadsnakes/ppa
                apt-get update
      - name: Set up Python ${{ matrix.python-version }}
        run: |
                apt-get install -y --no-install-recommends \
                  python${{ matrix.python-version }} \
                  python${{ matrix.python-version }}-dev \
                  python${{ matrix.python-version }}-venv \
                  python3-pip \
                  g++
                chown -R $(whoami) /github/home/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine
      - name: Build
        run: |
          python -m build --sdist --wheel .
      - name: Check the built archives
        run: |
          twine check dist/*
          pip install dist/*.whl
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_token }}
          repository_url: https://upload.pypi.org/legacy/
          verify_metadata: true
